---
title: "Evolution_pre_post_20202021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we are looking to the evolution between the pre test of 2020 and the post tests of 2021.
We have a total of 124 athletes who have taken those 2 tests. 

```{r}
#install.packages("readxl")
library("readxl")
data<-read_excel("Pre_et_post_tests_20202021.xlsx")
head(data)
new<-data.frame(data)
```

```{r fig.height=8, fig.width=8}
SPORT=new$Sport

SCORE_PRE=new$TotalPretest
SCORE_POST=new$TotalPosttest

par(mfrow=c(2,2))
boxplot(SCORE_PRE, main="Scores des pré tests 2020",cex.main=0.8,xlab="")
boxplot(SCORE_POST, main="Scores des post tests 2021",cex.main=0.8,xlab="")

hist(SCORE_PRE, main="Histogramme des scores des pré tests 2020",cex.main=0.8,xlab="")
hist(SCORE_POST, main="Histogramme des scores des post tests 2021",cex.main=0.8,xlab="")
```
```{r fig.height=8, fig.width=8}
color=c("red","blue","green","orange","purple","brown","darkblue","yellow")
DIFF=new$Diffprepost

par(mfrow=c(2,1))

plot(DIFF, type='p', col=color)
abline(a=0, b=0, col="black")
abline(a=5, b=0, col="black")

boxplot(DIFF~SPORT)

```

```{r fig.height=8, fig.width=8}
SPORT=new$Sport
par(mfrow=c(2,1))
boxplot(SCORE_PRE~SPORT, main="Pre test scores")
boxplot(SCORE_POST~SPORT,main="Post test scores")
```

```{r, warning=FALSE}
library(tidyverse)
library(hrbrthemes)
library(viridis)

par(mfrow=c(1,2))

new %>%
  ggplot( aes(x=SPORT, y=SCORE_PRE, fill=SPORT)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=8)
    ) +
    ggtitle("A boxplot with jitter") +
    xlab("")

new %>%
  ggplot( aes(x=SPORT, y=SCORE_POST, fill=SPORT)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=8)
    ) +
    ggtitle("A boxplot with jitter") +
    xlab("")
```


Here, we are looking to the difference of the post tests of 2021 and the pre tests of 2021.
We have a total of 42 athletes who have taken those 2 tests. 

```{r}
#install.packages("readxl")
library("readxl")
data<-read_excel("Post_et_pre_tests_2021.xlsx")
head(data)
new2<-data.frame(data)
```

```{r fig.height=8, fig.width=8}
NEW_SCORE_PRE=new2$TotalPretest
NEW_SCORE_POST=new2$TotalPosttest

par(mfrow=c(2,2))
boxplot(NEW_SCORE_POST, main="Scores des post tests 2021",cex.main=0.8,xlab="")
boxplot(NEW_SCORE_PRE, main="Scores des pré tests 2021",cex.main=0.8,xlab="")

hist(NEW_SCORE_POST, main="Histogramme des scores des post tests 2021",cex.main=0.8,xlab="")
hist(NEW_SCORE_PRE, main="Histogramme des scores des pré tests 2021",cex.main=0.8,xlab="")

```

```{r fig.height=8, fig.width=8}
color=c("red","blue","green","orange","purple","brown","darkblue","yellow")
NEW_DIFF=new2$Diff
NEW_SPORT=new2$Sport

par(mfrow=c(2,1))

plot(NEW_DIFF, type='p', col=color)
abline(a=0, b=0, col="black")
abline(a=-5, b=0, col="black")

boxplot(NEW_DIFF~NEW_SPORT)
```

```{r}
library(tidyverse)
library(hrbrthemes)
library(viridis)
par(mfrow=c(1,2))

new2 %>%
  ggplot( aes(x=NEW_SPORT, y=NEW_SCORE_PRE, fill=NEW_SPORT)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=8)
    ) +
    ggtitle("A boxplot with jitter") +
    xlab("")

new2 %>%
  ggplot( aes(x=NEW_SPORT, y=NEW_SCORE_POST, fill=NEW_SPORT)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_ipsum() +
    theme(
      legend.position="none",
      plot.title = element_text(size=8)
    ) +
    ggtitle("A boxplot with jitter") +
    xlab("")
```