---
title: "Models"
output: pdf_document
---

```{r}
library(ellipse)
library(leaps)
library(MASS)
library(corrplot)
library(glmnet)
library(plotly)
library(ggplot2)    
library(gridExtra)   
library(ggfortify)   
library(ggcorrplot)

datapre<-read_excel("Drive/RecappréTM2S20202021_curseurs_bis.xlsx")
datapost<-read_excel("Drive/RecappostTM2S20202021_curseurs_bis.xlsx")
injuries<-read_excel("Drive/Recapblessures20202021.xlsx")

nb_injuries=injuries$`Nb Bless`

totmobprecur=datapre$PourcMob_curseurs
totstabprecur=datapre$PourcStab_curseurs

totmobpostcur=datapost$PourcMob_curseurs
totstabpostcur=datapost$PourcStab_curseurs
```

```{r}
scatter_plot <- ggplot(datapre,aes(x=totmobprecur,y=totstabprecur)) + 
  geom_point() + 
  theme_minimal()

scatter_plot
```


```{r}
scatter_plot <- ggplot(datapost,aes(x=totmobpostcur,y=totstabpostcur)) + 
  geom_point() + 
  theme_minimal()

scatter_plot
```

```{r}
mod0 = lm(nb_injuries ~ totmobprecur+totstabprecur, data=datapre)
summary(mod0)

plot(nb_injuries~totmobprecur+totstabprecur)
abline(mod0, col="red")

res=resid(mod0)
plot(res)
```

```{r}
mod1 = lm(nb_injuries ~ totmobpostcur+totstabpostcur, data=datapost)
summary(mod1)
```

```{r}
totmobpre=datapre$PourcMob
totstabpre=datapre$PourcStab
scatter_plot <- ggplot(datapost,aes(x=totmobpre,y=totstabpre)) + 
  geom_point() + 
  theme_minimal()

scatter_plot
```

```{r}
totmobpost=datapost$PourcMob
totstabpost=datapost$PourcStab
scatter_plot <- ggplot(datapost,aes(x=totmobpost,y=totstabpost)) + 
  geom_point() + 
  theme_minimal()

scatter_plot
```

```{r}
mod2 = lm(nb_injuries ~ totmobpre+totstabpre, data=datapre)
summary(mod2)
```

```{r}
mod3 = lm(nb_injuries ~ totmobpost+totstabpost, data=datapost)
summary(mod3)
```
```{r}
anova(mod0)
anova(mod2)
```

```{r}
nb=nb_injuries
nb[nb>0]=1
glm = glm(nb~totmobpost+totstabpost, data=datapost, family=binomial(link="logit"))
summary(glm)

```